# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: true
# frozen_string_literal: true

source "https://rubygems.org"

# explicit require the local gems so that bundler can find them
gemspec path: "../idlc"
gemspec path: "../udb"
gemspec path: "../udb_helpers"

gemspec
