# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pdf-core` gem.
# Please instead update this file by running `bin/tapioca gem pdf-core`.


# source://pdf-core//lib/pdf/core/pdf_object.rb#11
module PDF; end

# source://pdf-core//lib/pdf/core/pdf_object.rb#12
module PDF::Core
  private

  # source://pdf-core//lib/pdf/core/pdf_object.rb#51
  def pdf_object(obj, in_content_stream = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/pdf_object.rb#15
  def real(num); end

  # source://pdf-core//lib/pdf/core/pdf_object.rb#19
  def real_params(array); end

  # source://pdf-core//lib/pdf/core/pdf_object.rb#31
  def string_to_hex(str); end

  # source://pdf-core//lib/pdf/core/pdf_object.rb#23
  def utf8_to_utf16(str); end

  class << self
    # source://pdf-core//lib/pdf/core/pdf_object.rb#51
    def pdf_object(obj, in_content_stream = T.unsafe(nil)); end

    # source://pdf-core//lib/pdf/core/pdf_object.rb#15
    def real(num); end

    # source://pdf-core//lib/pdf/core/pdf_object.rb#19
    def real_params(array); end

    # source://pdf-core//lib/pdf/core/pdf_object.rb#31
    def string_to_hex(str); end

    # source://pdf-core//lib/pdf/core/pdf_object.rb#23
    def utf8_to_utf16(str); end
  end
end

# source://pdf-core//lib/pdf/core/annotations.rb#13
module PDF::Core::Annotations
  # source://pdf-core//lib/pdf/core/annotations.rb#17
  def annotate(options); end

  # source://pdf-core//lib/pdf/core/annotations.rb#41
  def link_annotation(rect, options = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/annotations.rb#29
  def text_annotation(rect, contents, options = T.unsafe(nil)); end

  private

  # source://pdf-core//lib/pdf/core/annotations.rb#48
  def sanitize_annotation_hash(options); end
end

# source://pdf-core//lib/pdf/core/byte_string.rb#7
class PDF::Core::ByteString < ::String; end

# source://pdf-core//lib/pdf/core/destinations.rb#11
module PDF::Core::Destinations
  # source://pdf-core//lib/pdf/core/destinations.rb#31
  def add_dest(name, reference); end

  # source://pdf-core//lib/pdf/core/destinations.rb#46
  def dest_fit(dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#74
  def dest_fit_bounds(dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#81
  def dest_fit_bounds_horizontally(top, dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#88
  def dest_fit_bounds_vertically(left, dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#53
  def dest_fit_horizontally(top, dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#67
  def dest_fit_rect(left, bottom, right, top, dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#60
  def dest_fit_vertically(left, dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#39
  def dest_xyz(left, top, zoom = T.unsafe(nil), dest_page = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/destinations.rb#21
  def dests; end
end

# source://pdf-core//lib/pdf/core/destinations.rb#14
PDF::Core::Destinations::NAME_TREE_CHILDREN_LIMIT = T.let(T.unsafe(nil), Integer)

# source://pdf-core//lib/pdf/core/document_state.rb#5
class PDF::Core::DocumentState
  # source://pdf-core//lib/pdf/core/document_state.rb#6
  def initialize(options); end

  # source://pdf-core//lib/pdf/core/document_state.rb#63
  def before_render_actions(_doc); end

  # source://pdf-core//lib/pdf/core/document_state.rb#32
  def before_render_callbacks; end

  # source://pdf-core//lib/pdf/core/document_state.rb#32
  def before_render_callbacks=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def compress; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def compress=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def encrypt; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def encrypt=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def encryption_key; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def encryption_key=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#53
  def insert_page(page, page_number); end

  # source://pdf-core//lib/pdf/core/document_state.rb#45
  def normalize_metadata(options); end

  # source://pdf-core//lib/pdf/core/document_state.rb#59
  def on_page_create_action(doc); end

  # source://pdf-core//lib/pdf/core/document_state.rb#32
  def on_page_create_callback; end

  # source://pdf-core//lib/pdf/core/document_state.rb#32
  def on_page_create_callback=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def page; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def page=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#67
  def page_count; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def pages; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def pages=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#34
  def populate_pages_from_store(document); end

  # source://pdf-core//lib/pdf/core/document_state.rb#71
  def render_body(output); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def skip_encoding; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def skip_encoding=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def store; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def store=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def trailer; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def trailer=(_arg0); end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def version; end

  # source://pdf-core//lib/pdf/core/document_state.rb#31
  def version=(_arg0); end
end

# source://pdf-core//lib/pdf/core/pdf_object.rb#35
PDF::Core::ESCAPED_NAME_CHARACTERS = T.let(T.unsafe(nil), Array)

# source://pdf-core//lib/pdf/core.rb#25
module PDF::Core::Errors; end

# source://pdf-core//lib/pdf/core.rb#30
class PDF::Core::Errors::EmptyGraphicStateStack < ::StandardError; end

# source://pdf-core//lib/pdf/core.rb#27
class PDF::Core::Errors::FailedObjectConversion < ::StandardError; end

# source://pdf-core//lib/pdf/core.rb#34
class PDF::Core::Errors::InvalidPageLayout < ::StandardError; end

# source://pdf-core//lib/pdf/core/filter_list.rb#5
class PDF::Core::FilterList
  # source://pdf-core//lib/pdf/core/filter_list.rb#18
  def initialize; end

  # source://pdf-core//lib/pdf/core/filter_list.rb#22
  def <<(filter); end

  # source://pdf-core//lib/pdf/core/filter_list.rb#48
  def decode_params; end

  # source://pdf-core//lib/pdf/core/filter_list.rb#58
  def each(&block); end

  # source://pdf-core//lib/pdf/core/filter_list.rb#54
  def inspect; end

  # source://pdf-core//lib/pdf/core/filter_list.rb#42
  def names; end

  # source://pdf-core//lib/pdf/core/filter_list.rb#37
  def normalized; end

  # source://pdf-core//lib/pdf/core/filter_list.rb#40
  def to_a; end
end

# source://pdf-core//lib/pdf/core/filter_list.rb#6
class PDF::Core::FilterList::NotFilter < ::StandardError
  # source://pdf-core//lib/pdf/core/filter_list.rb#10
  def initialize(message = T.unsafe(nil), filter: T.unsafe(nil)); end
end

# source://pdf-core//lib/pdf/core/filter_list.rb#7
PDF::Core::FilterList::NotFilter::DEFAULT_MESSAGE = T.let(T.unsafe(nil), String)

# source://pdf-core//lib/pdf/core/filter_list.rb#8
PDF::Core::FilterList::NotFilter::MESSAGE_WITH_FILTER = T.let(T.unsafe(nil), String)

# source://pdf-core//lib/pdf/core/filters.rb#13
module PDF::Core::Filters; end

# source://pdf-core//lib/pdf/core/filters.rb#25
module PDF::Core::Filters::DCTDecode
  class << self
    # source://pdf-core//lib/pdf/core/filters.rb#30
    def decode(stream, _params = T.unsafe(nil)); end

    # source://pdf-core//lib/pdf/core/filters.rb#26
    def encode(stream, _params = T.unsafe(nil)); end
  end
end

# source://pdf-core//lib/pdf/core/filters.rb#14
module PDF::Core::Filters::FlateDecode
  class << self
    # source://pdf-core//lib/pdf/core/filters.rb#19
    def decode(stream, _params = T.unsafe(nil)); end

    # source://pdf-core//lib/pdf/core/filters.rb#15
    def encode(stream, _params = T.unsafe(nil)); end
  end
end

# source://pdf-core//lib/pdf/core/graphics_state.rb#46
class PDF::Core::GraphicState
  # source://pdf-core//lib/pdf/core/graphics_state.rb#49
  def initialize(previous_state = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def cap_style; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def cap_style=(_arg0); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def color_space; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def color_space=(_arg0); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def dash; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def dash=(_arg0); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#63
  def dash_setting; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def fill_color; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def fill_color=(_arg0); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def join_style; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def join_style=(_arg0); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def line_width; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def line_width=(_arg0); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def stroke_color; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#47
  def stroke_color=(_arg0); end

  private

  # source://pdf-core//lib/pdf/core/graphics_state.rb#79
  def initialize_copy(other); end
end

# source://pdf-core//lib/pdf/core/graphics_state.rb#13
class PDF::Core::GraphicStateStack
  # source://pdf-core//lib/pdf/core/graphics_state.rb#16
  def initialize(previous_state = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#32
  def current_state; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#40
  def empty?; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#36
  def present?; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#24
  def restore_graphic_state; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#20
  def save_graphic_state(graphic_state = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#14
  def stack; end

  # source://pdf-core//lib/pdf/core/graphics_state.rb#14
  def stack=(_arg0); end
end

# source://pdf-core//lib/pdf/core/literal_string.rb#14
class PDF::Core::LiteralString < ::String; end

# source://pdf-core//lib/pdf/core/name_tree.rb#13
module PDF::Core::NameTree; end

# source://pdf-core//lib/pdf/core/name_tree.rb#14
class PDF::Core::NameTree::Node
  # source://pdf-core//lib/pdf/core/name_tree.rb#21
  def initialize(document, limit, parent = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#74
  def <<(value); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#89
  def >=(other); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#41
  def add(name, value); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#15
  def children; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#107
  def deep_copy; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#17
  def document; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#29
  def empty?; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#66
  def greatest; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#37
  def leaf?; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#58
  def least; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#16
  def limit; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#18
  def parent; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#18
  def parent=(_arg0); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#19
  def ref; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#19
  def ref=(_arg0); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#33
  def size; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#93
  def split!; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#45
  def to_hash; end

  protected

  # source://pdf-core//lib/pdf/core/name_tree.rb#116
  def split(node); end

  private

  # source://pdf-core//lib/pdf/core/name_tree.rb#147
  def insertion_point(value); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#126
  def new_node(parent = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#132
  def split_children(node, left, right); end
end

# source://pdf-core//lib/pdf/core/name_tree.rb#155
class PDF::Core::NameTree::Value
  include ::Comparable

  # source://pdf-core//lib/pdf/core/name_tree.rb#161
  def initialize(name, value); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#166
  def <=>(other); end

  # source://pdf-core//lib/pdf/core/name_tree.rb#170
  def inspect; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#158
  def name; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#174
  def to_s; end

  # source://pdf-core//lib/pdf/core/name_tree.rb#159
  def value; end
end

# source://pdf-core//lib/pdf/core/object_store.rb#11
class PDF::Core::ObjectStore
  include ::Enumerable

  # source://pdf-core//lib/pdf/core/object_store.rb#16
  def initialize(opts = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/object_store.rb#67
  def <<(*args, &block); end

  # source://pdf-core//lib/pdf/core/object_store.rb#75
  def [](id); end

  # source://pdf-core//lib/pdf/core/object_store.rb#69
  def each; end

  # source://pdf-core//lib/pdf/core/object_store.rb#34
  def info; end

  # source://pdf-core//lib/pdf/core/object_store.rb#82
  def length; end

  # source://pdf-core//lib/pdf/core/object_store.rb#14
  def min_version; end

  # source://pdf-core//lib/pdf/core/object_store.rb#94
  def object_id_for_page(page); end

  # source://pdf-core//lib/pdf/core/object_store.rb#46
  def page_count; end

  # source://pdf-core//lib/pdf/core/object_store.rb#42
  def pages; end

  # source://pdf-core//lib/pdf/core/object_store.rb#54
  def push(*args, &block); end

  # source://pdf-core//lib/pdf/core/object_store.rb#30
  def ref(data, &block); end

  # source://pdf-core//lib/pdf/core/object_store.rb#38
  def root; end

  # source://pdf-core//lib/pdf/core/object_store.rb#79
  def size; end
end

# source://pdf-core//lib/pdf/core/outline_item.rb#5
class PDF::Core::OutlineItem
  # source://pdf-core//lib/pdf/core/outline_item.rb#8
  def initialize(title, parent, options); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def closed; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def closed=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def count; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def count=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def dest; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def dest=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def first; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def first=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def last; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def last=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def next; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def next=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def parent; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def parent=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def prev; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def prev=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def title; end

  # source://pdf-core//lib/pdf/core/outline_item.rb#6
  def title=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_item.rb#15
  def to_hash; end
end

# source://pdf-core//lib/pdf/core/outline_root.rb#5
class PDF::Core::OutlineRoot
  # source://pdf-core//lib/pdf/core/outline_root.rb#8
  def initialize; end

  # source://pdf-core//lib/pdf/core/outline_root.rb#6
  def count; end

  # source://pdf-core//lib/pdf/core/outline_root.rb#6
  def count=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_root.rb#6
  def first; end

  # source://pdf-core//lib/pdf/core/outline_root.rb#6
  def first=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_root.rb#6
  def last; end

  # source://pdf-core//lib/pdf/core/outline_root.rb#6
  def last=(_arg0); end

  # source://pdf-core//lib/pdf/core/outline_root.rb#12
  def to_hash; end
end

# source://pdf-core//lib/pdf/core/page.rb#14
class PDF::Core::Page
  # source://pdf-core//lib/pdf/core/page.rb#25
  def initialize(document, options = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/page.rb#165
  def art_box; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def art_indents; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def art_indents=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#175
  def bleed_box; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def bleeds; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def bleeds=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#100
  def content; end

  # source://pdf-core//lib/pdf/core/page.rb#16
  def content=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#185
  def crop_box; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def crops; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def crops=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#104
  def dictionary; end

  # source://pdf-core//lib/pdf/core/page.rb#16
  def dictionary=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#151
  def dimensions; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def document; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def document=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#133
  def ext_gstates; end

  # source://pdf-core//lib/pdf/core/page.rb#141
  def finalize; end

  # source://pdf-core//lib/pdf/core/page.rb#117
  def fonts; end

  # source://pdf-core//lib/pdf/core/page.rb#60
  def graphic_state; end

  # source://pdf-core//lib/pdf/core/page.rb#79
  def in_stamp_stream?; end

  # source://pdf-core//lib/pdf/core/page.rb#64
  def layout; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def margins; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def margins=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#109
  def resources; end

  # source://pdf-core//lib/pdf/core/page.rb#75
  def size; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def stack; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def stack=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#83
  def stamp_stream(dictionary); end

  # source://pdf-core//lib/pdf/core/page.rb#195
  def trim_box; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def trims; end

  # source://pdf-core//lib/pdf/core/page.rb#15
  def trims=(_arg0); end

  # source://pdf-core//lib/pdf/core/page.rb#125
  def xobjects; end

  private

  # source://pdf-core//lib/pdf/core/page.rb#215
  def inherited_dictionary_value(key, local_dict = T.unsafe(nil)); end
end

# source://pdf-core//lib/pdf/core/page.rb#18
PDF::Core::Page::ZERO_INDENTS = T.let(T.unsafe(nil), Hash)

# source://pdf-core//lib/pdf/core/page_geometry.rb#69
module PDF::Core::PageGeometry; end

# source://pdf-core//lib/pdf/core/page_geometry.rb#70
PDF::Core::PageGeometry::SIZES = T.let(T.unsafe(nil), Hash)

# source://pdf-core//lib/pdf/core/reference.rb#13
class PDF::Core::Reference
  # source://pdf-core//lib/pdf/core/reference.rb#22
  def initialize(id, data); end

  # source://pdf-core//lib/pdf/core/reference.rb#41
  def <<(io); end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def data; end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def data=(_arg0); end

  # source://pdf-core//lib/pdf/core/reference.rb#56
  def deep_copy(share = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def gen; end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def gen=(_arg0); end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def identifier; end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def identifier=(_arg0); end

  # source://pdf-core//lib/pdf/core/reference.rb#29
  def object; end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def offset; end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def offset=(_arg0); end

  # source://pdf-core//lib/pdf/core/reference.rb#76
  def replace(other_ref); end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def stream; end

  # source://pdf-core//lib/pdf/core/reference.rb#14
  def stream=(_arg0); end

  # source://pdf-core//lib/pdf/core/reference.rb#49
  def to_s; end
end

# source://pdf-core//lib/pdf/core/reference.rb#16
class PDF::Core::Reference::CannotAttachStream < ::StandardError
  # source://pdf-core//lib/pdf/core/reference.rb#17
  def initialize(message = T.unsafe(nil)); end
end

# source://pdf-core//lib/pdf/core/renderer.rb#7
class PDF::Core::Renderer
  # source://pdf-core//lib/pdf/core/renderer.rb#8
  def initialize(state); end

  # source://pdf-core//lib/pdf/core/renderer.rb#57
  def add_content(str); end

  # source://pdf-core//lib/pdf/core/renderer.rb#78
  def before_render(&block); end

  # source://pdf-core//lib/pdf/core/renderer.rb#237
  def close_graphics_state; end

  # source://pdf-core//lib/pdf/core/renderer.rb#253
  def compression_enabled?; end

  # source://pdf-core//lib/pdf/core/renderer.rb#44
  def deref(obj); end

  # source://pdf-core//lib/pdf/core/renderer.rb#139
  def finalize_all_page_contents; end

  # source://pdf-core//lib/pdf/core/renderer.rb#134
  def go_to_page(page_number); end

  # source://pdf-core//lib/pdf/core/renderer.rb#268
  def graphic_stack; end

  # source://pdf-core//lib/pdf/core/renderer.rb#272
  def graphic_state; end

  # source://pdf-core//lib/pdf/core/renderer.rb#153
  def min_version(min); end

  # source://pdf-core//lib/pdf/core/renderer.rb#66
  def names; end

  # source://pdf-core//lib/pdf/core/renderer.rb#72
  def names?; end

  # source://pdf-core//lib/pdf/core/renderer.rb#84
  def on_page_create(&block); end

  # source://pdf-core//lib/pdf/core/renderer.rb#233
  def open_graphics_state; end

  # source://pdf-core//lib/pdf/core/renderer.rb#125
  def page_count; end

  # source://pdf-core//lib/pdf/core/renderer.rb#24
  def ref(data); end

  # source://pdf-core//lib/pdf/core/renderer.rb#36
  def ref!(data); end

  # source://pdf-core//lib/pdf/core/renderer.rb#160
  def render(output = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/renderer.rb#199
  def render_body(output); end

  # source://pdf-core//lib/pdf/core/renderer.rb#181
  def render_file(filename); end

  # source://pdf-core//lib/pdf/core/renderer.rb#187
  def render_header(output); end

  # source://pdf-core//lib/pdf/core/renderer.rb#218
  def render_trailer(output); end

  # source://pdf-core//lib/pdf/core/renderer.rb#205
  def render_xref(output); end

  # source://pdf-core//lib/pdf/core/renderer.rb#259
  def restore_graphics_state; end

  # source://pdf-core//lib/pdf/core/renderer.rb#241
  def save_graphics_state(graphic_state = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/renderer.rb#91
  def start_new_page(options = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/renderer.rb#17
  def state; end
end

# source://pdf-core//lib/pdf/core/stream.rb#11
class PDF::Core::Stream
  # source://pdf-core//lib/pdf/core/stream.rb#14
  def initialize(io = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/stream.rb#20
  def <<(io); end

  # source://pdf-core//lib/pdf/core/stream.rb#26
  def compress!; end

  # source://pdf-core//lib/pdf/core/stream.rb#33
  def compressed?; end

  # source://pdf-core//lib/pdf/core/stream.rb#71
  def data; end

  # source://pdf-core//lib/pdf/core/stream.rb#37
  def empty?; end

  # source://pdf-core//lib/pdf/core/stream.rb#41
  def filtered_stream; end

  # source://pdf-core//lib/pdf/core/stream.rb#12
  def filters; end

  # source://pdf-core//lib/pdf/core/stream.rb#92
  def inspect; end

  # source://pdf-core//lib/pdf/core/stream.rb#59
  def length; end

  # source://pdf-core//lib/pdf/core/stream.rb#63
  def object; end
end

# source://pdf-core//lib/pdf/core/text.rb#11
module PDF::Core::Text
  # source://pdf-core//lib/pdf/core/text.rb#276
  def add_text_content(text, x, y, options); end

  # source://pdf-core//lib/pdf/core/text.rb#220
  def character_spacing(amount = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#70
  def default_kerning(boolean); end

  # source://pdf-core//lib/pdf/core/text.rb#74
  def default_kerning=(boolean); end

  # source://pdf-core//lib/pdf/core/text.rb#56
  def default_kerning?; end

  # source://pdf-core//lib/pdf/core/text.rb#88
  def default_leading(number = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#96
  def default_leading=(number = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#160
  def fallback_fonts(fallback_fonts = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#168
  def fallback_fonts=(fallback_fonts = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#212
  def forget_text_rendering_mode!; end

  # source://pdf-core//lib/pdf/core/text.rb#259
  def horizontal_text_scaling(amount = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#37
  def process_text_options(options); end

  # source://pdf-core//lib/pdf/core/text.rb#32
  def skip_encoding; end

  # source://pdf-core//lib/pdf/core/text.rb#118
  def text_direction(direction = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#126
  def text_direction=(direction = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#190
  def text_rendering_mode(mode = T.unsafe(nil)); end

  # source://pdf-core//lib/pdf/core/text.rb#241
  def word_spacing(amount = T.unsafe(nil)); end
end

# source://pdf-core//lib/pdf/core/text.rb#26
class PDF::Core::Text::BadFontFamily < ::StandardError
  # source://pdf-core//lib/pdf/core/text.rb#27
  def initialize(message = T.unsafe(nil)); end
end

# source://pdf-core//lib/pdf/core/text.rb#15
PDF::Core::Text::MODES = T.let(T.unsafe(nil), Hash)

# source://pdf-core//lib/pdf/core/text.rb#14
PDF::Core::Text::VALID_OPTIONS = T.let(T.unsafe(nil), Array)

# source://pdf-core//lib/pdf/core/utils.rb#5
module PDF::Core::Utils
  private

  # source://pdf-core//lib/pdf/core/utils.rb#8
  def deep_clone(object); end

  class << self
    # source://pdf-core//lib/pdf/core/utils.rb#8
    def deep_clone(object); end
  end
end
