# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prettyprint` gem.
# Please instead update this file by running `bin/tapioca gem prettyprint`.


class PrettyPrint
  # source://prettyprint//lib/prettyprint.rb#84
  def initialize(output = T.unsafe(nil), maxwidth = T.unsafe(nil), newline = T.unsafe(nil), &genspace); end

  # source://prettyprint//lib/prettyprint.rb#162
  def break_outmost_groups; end

  # source://prettyprint//lib/prettyprint.rb#226
  def breakable(sep = T.unsafe(nil), width = T.unsafe(nil)); end

  # source://prettyprint//lib/prettyprint.rb#157
  def current_group; end

  # source://prettyprint//lib/prettyprint.rb#214
  def fill_breakable(sep = T.unsafe(nil), width = T.unsafe(nil)); end

  # source://prettyprint//lib/prettyprint.rb#290
  def flush; end

  # source://prettyprint//lib/prettyprint.rb#120
  def genspace; end

  # source://prettyprint//lib/prettyprint.rb#251
  def group(indent = T.unsafe(nil), open_obj = T.unsafe(nil), close_obj = T.unsafe(nil), open_width = T.unsafe(nil), close_width = T.unsafe(nil)); end

  # source://prettyprint//lib/prettyprint.rb#126
  def group_queue; end

  # source://prettyprint//lib/prettyprint.rb#262
  def group_sub; end

  # source://prettyprint//lib/prettyprint.rb#123
  def indent; end

  # source://prettyprint//lib/prettyprint.rb#108
  def maxwidth; end

  # source://prettyprint//lib/prettyprint.rb#279
  def nest(indent); end

  # source://prettyprint//lib/prettyprint.rb#113
  def newline; end

  # source://prettyprint//lib/prettyprint.rb#103
  def output; end

  # source://prettyprint//lib/prettyprint.rb#182
  def text(obj, width = T.unsafe(nil)); end

  class << self
    # source://prettyprint//lib/prettyprint.rb#47
    def format(output = T.unsafe(nil), maxwidth = T.unsafe(nil), newline = T.unsafe(nil), genspace = T.unsafe(nil)); end

    # source://prettyprint//lib/prettyprint.rb#61
    def singleline_format(output = T.unsafe(nil), maxwidth = T.unsafe(nil), newline = T.unsafe(nil), genspace = T.unsafe(nil)); end
  end
end

class PrettyPrint::Breakable
  # source://prettyprint//lib/prettyprint.rb#347
  def initialize(sep, width, q); end

  # source://prettyprint//lib/prettyprint.rb#367
  def indent; end

  # source://prettyprint//lib/prettyprint.rb#359
  def obj; end

  # source://prettyprint//lib/prettyprint.rb#373
  def output(out, output_width); end

  # source://prettyprint//lib/prettyprint.rb#362
  def width; end
end

class PrettyPrint::Group
  # source://prettyprint//lib/prettyprint.rb#401
  def initialize(depth); end

  # source://prettyprint//lib/prettyprint.rb#414
  def break; end

  # source://prettyprint//lib/prettyprint.rb#419
  def break?; end

  # source://prettyprint//lib/prettyprint.rb#411
  def breakables; end

  # source://prettyprint//lib/prettyprint.rb#408
  def depth; end

  # source://prettyprint//lib/prettyprint.rb#426
  def first?; end
end

class PrettyPrint::GroupQueue
  # source://prettyprint//lib/prettyprint.rb#447
  def initialize(*groups); end

  # source://prettyprint//lib/prettyprint.rb#479
  def delete(group); end

  # source://prettyprint//lib/prettyprint.rb#463
  def deq; end

  # source://prettyprint//lib/prettyprint.rb#456
  def enq(group); end
end

class PrettyPrint::SingleLine
  # source://prettyprint//lib/prettyprint.rb#505
  def initialize(output, maxwidth = T.unsafe(nil), newline = T.unsafe(nil)); end

  # source://prettyprint//lib/prettyprint.rb#520
  def breakable(sep = T.unsafe(nil), width = T.unsafe(nil)); end

  # source://prettyprint//lib/prettyprint.rb#552
  def first?; end

  # source://prettyprint//lib/prettyprint.rb#548
  def flush; end

  # source://prettyprint//lib/prettyprint.rb#539
  def group(indent = T.unsafe(nil), open_obj = T.unsafe(nil), close_obj = T.unsafe(nil), open_width = T.unsafe(nil), close_width = T.unsafe(nil)); end

  # source://prettyprint//lib/prettyprint.rb#527
  def nest(indent); end

  # source://prettyprint//lib/prettyprint.rb#513
  def text(obj, width = T.unsafe(nil)); end
end

class PrettyPrint::Text
  # source://prettyprint//lib/prettyprint.rb#312
  def initialize; end

  # source://prettyprint//lib/prettyprint.rb#330
  def add(obj, width); end

  # source://prettyprint//lib/prettyprint.rb#323
  def output(out, output_width); end

  # source://prettyprint//lib/prettyprint.rb#318
  def width; end
end

# source://prettyprint//lib/prettyprint.rb#36
PrettyPrint::VERSION = T.let(T.unsafe(nil), String)
