# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-prof` gem.
# Please instead update this file by running `bin/tapioca gem ruby-prof`.


module ERB::Escape; end

# source://ruby-prof//lib/ruby-prof/rack.rb#4
module Rack; end

# source://ruby-prof//lib/ruby-prof/rack.rb#5
class Rack::RubyProf
  # source://ruby-prof//lib/ruby-prof/rack.rb#6
  def initialize(app, path: T.unsafe(nil), printers: T.unsafe(nil), skip_paths: T.unsafe(nil), only_paths: T.unsafe(nil), merge_fibers: T.unsafe(nil), measure_mode: T.unsafe(nil), track_allocations: T.unsafe(nil), exclude_common: T.unsafe(nil), ignore_existing_threads: T.unsafe(nil), request_thread_only: T.unsafe(nil), min_percent: T.unsafe(nil), sort_method: T.unsafe(nil)); end

  # source://ruby-prof//lib/ruby-prof/rack.rb#34
  def call(env); end

  private

  # source://ruby-prof//lib/ruby-prof/rack.rb#68
  def paths_match?(path, paths); end

  # source://ruby-prof//lib/ruby-prof/rack.rb#93
  def print(profile, path); end

  # source://ruby-prof//lib/ruby-prof/rack.rb#89
  def print_options; end

  # source://ruby-prof//lib/ruby-prof/rack.rb#72
  def profiling_options; end

  # source://ruby-prof//lib/ruby-prof/rack.rb#62
  def should_profile?(path); end
end

# source://ruby-prof//lib/ruby-prof/version.rb#1
module RubyProf
  class << self
    # source://ruby-prof//lib/ruby-prof.rb#36
    def figure_measure_mode; end
  end
end

RubyProf::ALLOCATIONS = T.let(T.unsafe(nil), Integer)

# source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#5
class RubyProf::AbstractPrinter
  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#15
  def initialize(result); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#20
  def filter_by; end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#20
  def max_percent; end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#66
  def method_href(thread, method); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#60
  def method_location(method); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#20
  def min_percent; end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#70
  def open_asset(file); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#51
  def print(output = T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg5); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#97
  def print_column_headers; end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#100
  def print_footer(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#87
  def print_header(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#81
  def print_thread(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#75
  def print_threads; end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#20
  def sort_method; end

  # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#23
  def time_format; end

  class << self
    # source://ruby-prof//lib/ruby-prof/printers/abstract_printer.rb#7
    def needs_dir?; end
  end
end

class RubyProf::Allocation
  # source://ruby-prof//lib/ruby-prof.rb#9
  def _dump_data; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _load_data(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def count; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def klass_flags; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def klass_name; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def line; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def source_file; end
end

RubyProf::CLOCKS_PER_SEC = T.let(T.unsafe(nil), Integer)

# source://ruby-prof//lib/ruby-prof/printers/call_info_printer.rb#16
class RubyProf::CallInfoPrinter < ::RubyProf::AbstractPrinter
  private

  # source://ruby-prof//lib/ruby-prof/printers/call_info_printer.rb#49
  def print_footer(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/call_info_printer.rb#21
  def print_header(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/call_info_printer.rb#30
  def print_methods(thread); end
end

# source://ruby-prof//lib/ruby-prof/printers/call_info_printer.rb#17
RubyProf::CallInfoPrinter::TIME_WIDTH = T.let(T.unsafe(nil), Integer)

# source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#21
class RubyProf::CallStackPrinter < ::RubyProf::AbstractPrinter
  include ::ERB::Escape
  include ::ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#151
  def application; end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#153
  def arguments; end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#157
  def base64_image; end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#138
  def color(p); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#134
  def dump(ci); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#151
  def expansion; end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#116
  def graph_link(call_tree); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#106
  def link(method, recursive); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#122
  def method_href(method); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#101
  def name(call_tree); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#46
  def print(output = T.unsafe(nil), title: T.unsafe(nil), threshold: T.unsafe(nil), expansion: T.unsafe(nil), application: T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg9); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#60
  def print_stack(output, visited, call_tree, parent_time); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#130
  def sum(a); end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#164
  def template; end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#151
  def threshold; end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#151
  def title; end

  # source://ruby-prof//lib/ruby-prof/printers/call_stack_printer.rb#126
  def total_time(call_trees); end
end

# source://ruby-prof//lib/ruby-prof/call_tree.rb#8
class RubyProf::CallTree
  # source://ruby-prof//lib/ruby-prof.rb#9
  def initialize(_arg0); end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#36
  def <=>(other); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _dump_data; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _load_data(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def add_child(_arg0); end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#10
  def called; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def children; end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#30
  def children_time; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def depth; end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#53
  def inspect; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def line; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def measurement; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def parent; end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#20
  def self_time; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def source_file; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def target; end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#49
  def to_s; end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#15
  def total_time; end

  # source://ruby-prof//lib/ruby-prof/call_tree.rb#25
  def wait_time; end
end

# source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#12
class RubyProf::CallTreePrinter < ::RubyProf::AbstractPrinter
  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#13
  def calltree_name(method_info); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#65
  def convert(value); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#29
  def determine_event_specification_and_value_scale; end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#69
  def file(method); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#94
  def file_name_for_thread(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#102
  def file_path_for_thread(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#82
  def path; end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#52
  def print(path: T.unsafe(nil), **_arg1); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#106
  def print_headers(output, thread); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#112
  def print_method(output, method); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#73
  def print_thread(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#58
  def print_threads; end

  # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#88
  def remove_subsidiary_files_from_previous_profile_runs; end

  class << self
    # source://ruby-prof//lib/ruby-prof/printers/call_tree_printer.rb#84
    def needs_dir?; end
  end
end

# source://ruby-prof//lib/ruby-prof/call_tree_visitor.rb#17
class RubyProf::CallTreeVisitor
  # source://ruby-prof//lib/ruby-prof/call_tree_visitor.rb#18
  def initialize(call_tree); end

  # source://ruby-prof//lib/ruby-prof/call_tree_visitor.rb#22
  def visit(&block); end

  private

  # source://ruby-prof//lib/ruby-prof/call_tree_visitor.rb#28
  def visit_call_tree(call_tree, &block); end
end

class RubyProf::CallTrees
  # source://ruby-prof//lib/ruby-prof.rb#9
  def _dump_data; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _load_data(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def call_trees; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def callees; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def callers; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def min_depth; end
end

# source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#22
class RubyProf::DotPrinter < ::RubyProf::AbstractPrinter
  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#26
  def initialize(result); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#45
  def print(output = T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg5); end

  private

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#88
  def color_for_class(klass_name); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#84
  def dot_id(subject); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#68
  def mode_name; end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#96
  def node_color(total_percentage); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#110
  def node_fontcolor(total_percentage); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#135
  def print_classes(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#160
  def print_edges(total_time, method); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#114
  def print_thread(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#72
  def print_threads; end

  # source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#172
  def puts(str); end
end

# source://ruby-prof//lib/ruby-prof/printers/dot_printer.rb#23
RubyProf::DotPrinter::CLUSTER_COLORS = T.let(T.unsafe(nil), Array)

# source://ruby-prof//lib/ruby-prof/exclude_common_methods.rb#5
module RubyProf::ExcludeCommonMethods
  class << self
    # source://ruby-prof//lib/ruby-prof/exclude_common_methods.rb#8
    def apply!(profile); end

    # source://ruby-prof//lib/ruby-prof/exclude_common_methods.rb#191
    def exclude_enumerable(profile, mod, *method_or_methods); end

    # source://ruby-prof//lib/ruby-prof/exclude_common_methods.rb#196
    def exclude_methods(profile, mod, *method_or_methods); end

    # source://ruby-prof//lib/ruby-prof/exclude_common_methods.rb#200
    def exclude_singleton_methods(profile, mod, *method_or_methods); end
  end
end

# source://ruby-prof//lib/ruby-prof/exclude_common_methods.rb#6
RubyProf::ExcludeCommonMethods::ENUMERABLE_NAMES = T.let(T.unsafe(nil), Array)

# source://ruby-prof//lib/ruby-prof/printers/flame_graph_printer.rb#18
class RubyProf::FlameGraphPrinter < ::RubyProf::AbstractPrinter
  include ::ERB::Escape
  include ::ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate

  # source://ruby-prof//lib/ruby-prof/printers/flame_graph_printer.rb#43
  def build_flame_data(call_tree, visited = T.unsafe(nil)); end

  # source://ruby-prof//lib/ruby-prof/printers/flame_graph_printer.rb#63
  def flame_data_json; end

  # source://ruby-prof//lib/ruby-prof/printers/flame_graph_printer.rb#31
  def print(output = T.unsafe(nil), title: T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg6); end

  # source://ruby-prof//lib/ruby-prof/printers/flame_graph_printer.rb#75
  def template; end

  # source://ruby-prof//lib/ruby-prof/printers/flame_graph_printer.rb#41
  def title; end
end

# source://ruby-prof//lib/ruby-prof/printers/flat_printer.rb#14
class RubyProf::FlatPrinter < ::RubyProf::AbstractPrinter
  # source://ruby-prof//lib/ruby-prof/printers/flat_printer.rb#16
  def print(output = T.unsafe(nil), sort_method: T.unsafe(nil), **options); end

  private

  # source://ruby-prof//lib/ruby-prof/printers/flat_printer.rb#22
  def print_column_headers; end

  # source://ruby-prof//lib/ruby-prof/printers/flat_printer.rb#26
  def print_methods(thread); end
end

# source://ruby-prof//lib/ruby-prof/printers/graph_html_printer.rb#16
class RubyProf::GraphHtmlPrinter < ::RubyProf::AbstractPrinter
  include ::ERB::Escape
  include ::ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate

  # source://ruby-prof//lib/ruby-prof/printers/graph_html_printer.rb#34
  def create_link(thread, overall_time, method); end

  # source://ruby-prof//lib/ruby-prof/printers/graph_html_printer.rb#49
  def file_link(path, linenum); end

  # source://ruby-prof//lib/ruby-prof/printers/graph_html_printer.rb#45
  def method_href(thread, method); end

  # source://ruby-prof//lib/ruby-prof/printers/graph_html_printer.rb#19
  def print(output = T.unsafe(nil), min_time: T.unsafe(nil), nonzero: T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg7); end

  # source://ruby-prof//lib/ruby-prof/printers/graph_html_printer.rb#58
  def template; end
end

# source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#14
class RubyProf::GraphPrinter < ::RubyProf::AbstractPrinter
  # source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#20
  def print(output = T.unsafe(nil), sort_method: T.unsafe(nil), **options); end

  private

  # source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#94
  def print_children(method); end

  # source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#26
  def print_header(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#47
  def print_methods(thread); end

  # source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#79
  def print_parents(thread, method); end
end

# source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#17
RubyProf::GraphPrinter::CALL_WIDTH = T.let(T.unsafe(nil), Integer)

# source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#15
RubyProf::GraphPrinter::PERCENTAGE_WIDTH = T.let(T.unsafe(nil), Integer)

# source://ruby-prof//lib/ruby-prof/printers/graph_printer.rb#16
RubyProf::GraphPrinter::TIME_WIDTH = T.let(T.unsafe(nil), Integer)

module RubyProf::Measure; end
class RubyProf::Measure::Allocations; end
class RubyProf::Measure::ProcessTime; end
class RubyProf::Measure::WallTime; end

# source://ruby-prof//lib/ruby-prof/measurement.rb#4
class RubyProf::Measurement
  # source://ruby-prof//lib/ruby-prof.rb#9
  def initialize(_arg0, _arg1, _arg2, _arg3); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _dump_data; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _load_data(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def called; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def called=(_arg0); end

  # source://ruby-prof//lib/ruby-prof/measurement.rb#5
  def children_time; end

  # source://ruby-prof//lib/ruby-prof/measurement.rb#13
  def inspect; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def merge!(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def self_time; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def self_time=(_arg0); end

  # source://ruby-prof//lib/ruby-prof/measurement.rb#9
  def to_s; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def total_time; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def total_time=(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def wait_time; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def wait_time=(_arg0); end

  private

  # source://ruby-prof//lib/ruby-prof.rb#9
  def initialize_copy(_arg0); end
end

# source://ruby-prof//lib/ruby-prof/method_info.rb#6
class RubyProf::MethodInfo
  include ::Comparable

  # source://ruby-prof//lib/ruby-prof.rb#9
  def initialize(_arg0, _arg1); end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#63
  def <=>(other); end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#59
  def ==(other); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _dump_data; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _load_data(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def allocations; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def call_trees; end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#31
  def called; end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#51
  def children_time; end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#55
  def eql?(other); end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#15
  def full_name; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def hash; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def klass_flags; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def klass_name; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def line; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def measurement; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def method_name; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def recursive?; end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#41
  def self_time; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def source_file; end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#83
  def to_s; end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#36
  def total_time; end

  # source://ruby-prof//lib/ruby-prof/method_info.rb#46
  def wait_time; end
end

RubyProf::MethodInfo::CLASS_SINGLETON = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::MODULE_INCLUDEE = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::MODULE_SINGLETON = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::OBJECT_SINGLETON = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::OTHER_SINGLETON = T.let(T.unsafe(nil), Integer)

# source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#7
class RubyProf::MultiPrinter
  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#8
  def initialize(result, printers = T.unsafe(nil)); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#64
  def call_info_report; end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#84
  def dot_report; end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#79
  def flame_graph_report; end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#50
  def flat_report; end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#59
  def graph_html_report; end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#55
  def graph_report; end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#33
  def print(profile: T.unsafe(nil), path: T.unsafe(nil), **options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#106
  def print_to_call_info(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#128
  def print_to_dot(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#122
  def print_to_flame_graph(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#88
  def print_to_flat(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#94
  def print_to_graph(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#100
  def print_to_graph_html(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#116
  def print_to_stack(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#112
  def print_to_tree(**options); end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#74
  def stack_report; end

  # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#69
  def tree_report; end

  class << self
    # source://ruby-prof//lib/ruby-prof/printers/multi_printer.rb#22
    def needs_dir?; end
  end
end

RubyProf::PROCESS_TIME = T.let(T.unsafe(nil), Integer)

# source://ruby-prof//lib/ruby-prof/profile.rb#6
class RubyProf::Profile
  # source://ruby-prof//lib/ruby-prof.rb#9
  def initialize(*_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _dump_data; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _load_data(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def add_thread(_arg0); end

  # source://ruby-prof//lib/ruby-prof/profile.rb#35
  def exclude_common_methods!; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def exclude_method!(_arg0, _arg1); end

  # source://ruby-prof//lib/ruby-prof/profile.rb#39
  def exclude_methods!(mod, *method_names); end

  # source://ruby-prof//lib/ruby-prof/profile.rb#45
  def exclude_singleton_methods!(mod, *method_names); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def measure_mode; end

  # source://ruby-prof//lib/ruby-prof/profile.rb#20
  def measure_mode_name; end

  # source://ruby-prof//lib/ruby-prof/profile.rb#7
  def measure_mode_string; end

  # source://ruby-prof//lib/ruby-prof/profile.rb#61
  def merge!; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def pause; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def paused?; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def profile; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def remove_thread(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def resume; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def running?; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def start; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def stop; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def threads; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def track_allocations?; end

  class << self
    # source://ruby-prof//lib/ruby-prof.rb#9
    def profile(*_arg0); end
  end
end

# source://ruby-prof//lib/ruby-prof/thread.rb#2
class RubyProf::Thread
  # source://ruby-prof//lib/ruby-prof.rb#9
  def initialize(_arg0, _arg1, _arg2); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _dump_data; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def _load_data(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def call_tree; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def fiber_id; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def id; end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def merge!(_arg0); end

  # source://ruby-prof//lib/ruby-prof.rb#9
  def methods; end

  # source://ruby-prof//lib/ruby-prof/thread.rb#4
  def total_time; end

  # source://ruby-prof//lib/ruby-prof/thread.rb#9
  def wait_time; end
end

# source://ruby-prof//lib/ruby-prof/version.rb#2
RubyProf::VERSION = T.let(T.unsafe(nil), String)

RubyProf::WALL_TIME = T.let(T.unsafe(nil), Integer)
