# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: false
# frozen_string_literal: true

require "yaml"

regress_template_yaml = YAML.load_file(Pathname.new(__dir__) / "regress-gh-template.yaml")
# make a deep copy
regress_yaml = YAML.load(YAML.dump(regress_template_yaml))
tests = YAML.load_file(Pathname.new(__dir__) / "regress-tests.yaml")

def create_job(job_name, job_data, workflow_yaml)
  gh_job_yaml = {
    "runs-on" => "ubuntu-latest",
    "needs" => "build-container",
    "steps" => [
      {
        "name" => "Clone Github Repo Action",
        "uses" => workflow_yaml["jobs"]["build-container"]["steps"][0]["uses"]
      },
      {
        "name" => "Download docker image",
        "uses" => workflow_yaml["jobs"]["never-runs"]["steps"][0]["uses"],
        "with" => {
          "name" => "docker_image",
          "path" => "${{ runner.temp }}"
        }
      },
      {
        "name" => "Load image",
        "run" => "docker load --input ${{ runner.temp }}/docker_image.tar"
      }
    ]
  }

  if job_data["ci_stage"] == "merge_queue"
    gh_job_yaml["if"] = "(github.event_name == 'merge_queue') || ((github.event_name == 'push') && (github.ref_name == 'main'))"
  end

  if job_data.key?("env")
    gh_job_yaml["env"] = job_data["env"]
  end

  if job_data.key?("strategy")
    gh_job_yaml["strategy"] = job_data["strategy"]
  end

  if job_data.key?("gh_pre")
    gh_job_yaml["steps"].concat(job_data["gh_pre"])
  end

  gh_job_yaml["steps"].concat(job_data["test"])

  if job_data.key?("gh_post")
    gh_job_yaml["steps"].concat(job_data["gh_post"])
  end

  if job_data.key?("gh_save_artifact")
    job_data["gh_save_artifact"].each do |artifact|
      gh_job_yaml["steps"] << {
        "name" => "Upload artifact",
        "uses" => workflow_yaml["jobs"]["never-runs"]["steps"][1]["uses"],
        "if" => "((github.event_name == 'push') && (github.ref_name == 'main'))",
        "with" => {
          "name" => artifact["artifact_name"],
          "path" => artifact["path"]
        }
      }
      if artifact["include-hidden-files"]
        gh_job_yaml["steps"].last["with"]["include-hidden-files"] = true
      end
    end
  end

  gh_job_yaml
end

tests["tests"].each do |test_name, test_data|
  if ["pr", "merge_queue"].include?(test_data["ci_stage"])
    regress_yaml["jobs"][test_name] = create_job(test_name, test_data, regress_yaml)

  else
    raise "bad ci_stage: #{test_data["ci_stage"]}"
  end
end

regress_yaml["jobs"]["regress-complete"] = {
  "runs-on" => "ubuntu-latest",
  "needs" => tests["tests"].keys + (regress_template_yaml["jobs"].keys - ["build-container", "never-runs"]),
  "if" => "${{ always() }}",
  "steps" => [
    {
      "name" => "exit failure",
      "if" => "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}",
      "run" => "exit 1"
    },
    {
      "name" => "exit success",
      "if" => "${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}",
      "run" => "exit 0"
    }
  ]
}

f = <<~FILE.strip
# This file was generated by `./bin/chore gen regress`
# DO NOT EDIT
# Instead, edit `tools/test/regress-tests.yaml` (preferred) or `tools/test/regress-gh-template.yaml`

#{YAML.dump(regress_yaml, line_width: 300)}
FILE
File.write (Pathname.new(__dir__) / ".." / ".." / ".github" / "workflows" / "regress.yml"), "#{f}\n"
