# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `erb` gem.
# Please instead update this file by running `bin/tapioca gem erb`.


# source://erb//lib/erb/version.rb#2
class ERB
  # source://erb//lib/erb.rb#832
  def initialize(str, trim_mode: T.unsafe(nil), eoutvar: T.unsafe(nil)); end

  # source://erb//lib/erb.rb#1170
  def def_class(superklass = T.unsafe(nil), methodname = T.unsafe(nil)); end

  # source://erb//lib/erb.rb#1088
  def def_method(mod, methodname, fname = T.unsafe(nil)); end

  # source://erb//lib/erb.rb#1113
  def def_module(methodname = T.unsafe(nil)); end

  # source://erb//lib/erb.rb#909
  def encoding; end

  # source://erb//lib/erb.rb#917
  def filename; end

  # source://erb//lib/erb.rb#917
  def filename=(_arg0); end

  # source://erb//lib/erb.rb#925
  def lineno; end

  # source://erb//lib/erb.rb#925
  def lineno=(_arg0); end

  # source://erb//lib/erb.rb#937
  def location=(_arg0); end

  # source://erb//lib/erb.rb#854
  def make_compiler(trim_mode); end

  # source://erb//lib/erb.rb#1008
  def result(b = T.unsafe(nil)); end

  # source://erb//lib/erb.rb#1027
  def result_with_hash(hash); end

  # source://erb//lib/erb.rb#986
  def run(b = T.unsafe(nil)); end

  # source://erb//lib/erb.rb#972
  def set_eoutvar(compiler, eoutvar = T.unsafe(nil)); end

  # source://erb//lib/erb.rb#900
  def src; end

  private

  # source://erb//lib/erb.rb#1051
  def new_toplevel(vars = T.unsafe(nil)); end

  class << self
    # source://erb//lib/erb.rb#787
    def version; end
  end
end

# source://erb//lib/erb/compiler.rb#73
class ERB::Compiler
  # source://erb//lib/erb/compiler.rb#433
  def initialize(trim_mode); end

  # source://erb//lib/erb/compiler.rb#315
  def add_insert_cmd(out, content); end

  # source://erb//lib/erb/compiler.rb#311
  def add_put_cmd(out, content); end

  # source://erb//lib/erb/compiler.rb#321
  def compile(s); end

  # source://erb//lib/erb/compiler.rb#381
  def compile_content(stag, out); end

  # source://erb//lib/erb/compiler.rb#368
  def compile_etag(etag, out, scanner); end

  # source://erb//lib/erb/compiler.rb#344
  def compile_stag(stag, out, scanner); end

  # source://erb//lib/erb/compiler.rb#446
  def insert_cmd; end

  # source://erb//lib/erb/compiler.rb#446
  def insert_cmd=(_arg0); end

  # source://erb//lib/erb/compiler.rb#427
  def make_scanner(src); end

  # source://erb//lib/erb/compiler.rb#440
  def percent; end

  # source://erb//lib/erb/compiler.rb#452
  def post_cmd; end

  # source://erb//lib/erb/compiler.rb#452
  def post_cmd=(_arg0); end

  # source://erb//lib/erb/compiler.rb#449
  def pre_cmd; end

  # source://erb//lib/erb/compiler.rb#449
  def pre_cmd=(_arg0); end

  # source://erb//lib/erb/compiler.rb#398
  def prepare_trim_mode(mode); end

  # source://erb//lib/erb/compiler.rb#443
  def put_cmd; end

  # source://erb//lib/erb/compiler.rb#443
  def put_cmd=(_arg0); end

  # source://erb//lib/erb/compiler.rb#440
  def trim_mode; end

  private

  # source://erb//lib/erb/compiler.rb#457
  def content; end

  # source://erb//lib/erb/compiler.rb#457
  def content=(_arg0); end

  # source://erb//lib/erb/compiler.rb#459
  def detect_magic_comment(s, enc = T.unsafe(nil)); end

  # source://erb//lib/erb/compiler.rb#484
  def warn_invalid_trim_mode(mode, uplevel:); end
end

# source://erb//lib/erb/compiler.rb#278
class ERB::Compiler::Buffer
  # source://erb//lib/erb/compiler.rb#279
  def initialize(compiler, enc = T.unsafe(nil), frozen = T.unsafe(nil)); end

  # source://erb//lib/erb/compiler.rb#301
  def close; end

  # source://erb//lib/erb/compiler.rb#295
  def cr; end

  # source://erb//lib/erb/compiler.rb#291
  def push(cmd); end

  # source://erb//lib/erb/compiler.rb#289
  def script; end
end

# source://erb//lib/erb/compiler.rb#254
class ERB::Compiler::ExplicitScanner < ::ERB::Compiler::Scanner
  # source://erb//lib/erb/compiler.rb#255
  def scan; end
end

# source://erb//lib/erb/compiler.rb#74
class ERB::Compiler::PercentLine
  # source://erb//lib/erb/compiler.rb#75
  def initialize(str); end

  # source://erb//lib/erb/compiler.rb#79
  def to_s; end

  # source://erb//lib/erb/compiler.rb#78
  def value; end
end

# source://erb//lib/erb/compiler.rb#82
class ERB::Compiler::Scanner
  # source://erb//lib/erb/compiler.rb#108
  def initialize(src, trim_mode, percent); end

  # source://erb//lib/erb/compiler.rb#115
  def etags; end

  # source://erb//lib/erb/compiler.rb#117
  def scan; end

  # source://erb//lib/erb/compiler.rb#114
  def stag; end

  # source://erb//lib/erb/compiler.rb#114
  def stag=(_arg0); end

  # source://erb//lib/erb/compiler.rb#115
  def stags; end

  class << self
    # source://erb//lib/erb/compiler.rb#97
    def default_scanner=(klass); end

    # source://erb//lib/erb/compiler.rb#101
    def make_scanner(src, trim_mode, percent); end

    # source://erb//lib/erb/compiler.rb#94
    def regist_scanner(klass, trim_mode, percent); end

    # source://erb//lib/erb/compiler.rb#86
    def register_scanner(klass, trim_mode, percent); end
  end
end

# source://erb//lib/erb/compiler.rb#107
ERB::Compiler::Scanner::DEFAULT_ETAGS = T.let(T.unsafe(nil), Array)

# source://erb//lib/erb/compiler.rb#106
ERB::Compiler::Scanner::DEFAULT_STAGS = T.let(T.unsafe(nil), Array)

# source://erb//lib/erb/compiler.rb#240
class ERB::Compiler::SimpleScanner < ::ERB::Compiler::Scanner
  # source://erb//lib/erb/compiler.rb#241
  def scan; end
end

# source://erb//lib/erb/compiler.rb#120
class ERB::Compiler::TrimScanner < ::ERB::Compiler::Scanner
  # source://erb//lib/erb/compiler.rb#121
  def initialize(src, trim_mode, percent); end

  # source://erb//lib/erb/compiler.rb#210
  def explicit_trim_line(line); end

  # source://erb//lib/erb/compiler.rb#229
  def is_erb_stag?(s); end

  # source://erb//lib/erb/compiler.rb#152
  def percent_line(line, &block); end

  # source://erb//lib/erb/compiler.rb#140
  def scan(&block); end

  # source://erb//lib/erb/compiler.rb#165
  def scan_line(line); end

  # source://erb//lib/erb/compiler.rb#174
  def trim_line1(line); end

  # source://erb//lib/erb/compiler.rb#188
  def trim_line2(line); end
end

# source://erb//lib/erb/compiler.rb#476
ERB::Compiler::WARNING_UPLEVEL = T.let(T.unsafe(nil), Integer)

# source://erb//lib/erb/def_method.rb#33
module ERB::DefMethod
  private

  # source://erb//lib/erb/def_method.rb#36
  def def_erb_method(methodname, erb_or_fname); end

  class << self
    # source://erb//lib/erb/def_method.rb#46
    def def_erb_method(methodname, erb_or_fname); end
  end
end

module ERB::Escape; end

# source://erb//lib/erb/util.rb#33
module ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ERB::Escape
  extend ::ActiveSupport::CoreExt::ERBUtil

  private

  # source://erb//lib/erb/util.rb#74
  def u(s); end

  # source://erb//lib/erb/util.rb#64
  def url_encode(s); end

  class << self
    # source://erb//lib/erb/util.rb#49
    def h(s); end

    # source://erb//lib/erb/util.rb#47
    def html_escape(s); end

    # source://erb//lib/erb/util.rb#75
    def u(s); end

    # source://erb//lib/erb/util.rb#76
    def url_encode(s); end
  end
end

# source://erb//lib/erb/version.rb#4
ERB::VERSION = T.let(T.unsafe(nil), String)
