# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `psych` gem.
# Please instead update this file by running `bin/tapioca gem psych`.


# source://psych//lib/psych/core_ext.rb#2
class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
  include ::Udb::Helpers::WavedromUtil

  # source://psych//lib/psych/core_ext.rb#12
  def to_yaml(options = T.unsafe(nil)); end

  class << self
    # source://psych//lib/psych/core_ext.rb#3
    def yaml_tag(url); end
  end
end

# source://psych//lib/psych/versions.rb#3
module Psych
  class << self
    # source://psych//lib/psych.rb#729
    def add_builtin_type(type_tag, &block); end

    # source://psych//lib/psych.rb#723
    def add_domain_type(domain, type_tag, &block); end

    # source://psych//lib/psych.rb#739
    def add_tag(tag, klass); end

    # source://psych//lib/psych.rb#755
    def config; end

    # source://psych//lib/psych.rb#767
    def domain_types; end

    # source://psych//lib/psych.rb#779
    def domain_types=(value); end

    # source://psych//lib/psych.rb#515
    def dump(o, io = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://psych//lib/psych.rb#613
    def dump_stream(*objects); end

    # source://psych//lib/psych.rb#763
    def dump_tags; end

    # source://psych//lib/psych.rb#775
    def dump_tags=(value); end

    # source://psych//lib/psych.rb#15
    def libyaml_version; end

    # source://psych//lib/psych.rb#369
    def load(yaml, permitted_classes: T.unsafe(nil), permitted_symbols: T.unsafe(nil), aliases: T.unsafe(nil), filename: T.unsafe(nil), fallback: T.unsafe(nil), symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil), parse_symbols: T.unsafe(nil)); end

    # source://psych//lib/psych.rb#716
    def load_file(filename, **kwargs); end

    # source://psych//lib/psych.rb#644
    def load_stream(yaml, filename: T.unsafe(nil), fallback: T.unsafe(nil), **kwargs); end

    # source://psych//lib/psych.rb#759
    def load_tags; end

    # source://psych//lib/psych.rb#771
    def load_tags=(value); end

    # source://psych//lib/psych.rb#400
    def parse(yaml, filename: T.unsafe(nil)); end

    # source://psych//lib/psych.rb#412
    def parse_file(filename, fallback: T.unsafe(nil)); end

    # source://psych//lib/psych.rb#454
    def parse_stream(yaml, filename: T.unsafe(nil), &block); end

    # source://psych//lib/psych.rb#421
    def parser; end

    # source://psych//lib/psych.rb#735
    def remove_type(type_tag); end

    # source://psych//lib/psych.rb#596
    def safe_dump(o, io = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://psych//lib/psych.rb#323
    def safe_load(yaml, permitted_classes: T.unsafe(nil), permitted_symbols: T.unsafe(nil), aliases: T.unsafe(nil), filename: T.unsafe(nil), fallback: T.unsafe(nil), symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil), parse_symbols: T.unsafe(nil)); end

    # source://psych//lib/psych.rb#705
    def safe_load_file(filename, **kwargs); end

    # source://psych//lib/psych.rb#671
    def safe_load_stream(yaml, filename: T.unsafe(nil), permitted_classes: T.unsafe(nil), aliases: T.unsafe(nil)); end

    # source://psych//lib/psych.rb#623
    def to_json(object); end

    # source://psych//lib/psych.rb#272
    def unsafe_load(yaml, filename: T.unsafe(nil), fallback: T.unsafe(nil), symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil), parse_symbols: T.unsafe(nil)); end

    # source://psych//lib/psych.rb#694
    def unsafe_load_file(filename, **kwargs); end
  end
end

# source://psych//lib/psych/exception.rb#10
class Psych::AliasesNotEnabled < ::Psych::BadAlias
  # source://psych//lib/psych/exception.rb#11
  def initialize; end
end

# source://psych//lib/psych/exception.rb#17
class Psych::AnchorNotDefined < ::Psych::BadAlias
  # source://psych//lib/psych/exception.rb#18
  def initialize(anchor_name); end
end

# source://psych//lib/psych/class_loader.rb#6
class Psych::ClassLoader
  # source://psych//lib/psych/class_loader.rb#22
  def initialize; end

  # source://psych//lib/psych/class_loader.rb#39
  def big_decimal; end

  # source://psych//lib/psych/class_loader.rb#39
  def complex; end

  # source://psych//lib/psych/class_loader.rb#39
  def data; end

  # source://psych//lib/psych/class_loader.rb#39
  def date; end

  # source://psych//lib/psych/class_loader.rb#39
  def date_time; end

  # source://psych//lib/psych/class_loader.rb#39
  def exception; end

  # source://psych//lib/psych/class_loader.rb#26
  def load(klassname); end

  # source://psych//lib/psych/class_loader.rb#39
  def object; end

  # source://psych//lib/psych/class_loader.rb#39
  def psych_omap; end

  # source://psych//lib/psych/class_loader.rb#39
  def psych_set; end

  # source://psych//lib/psych/class_loader.rb#39
  def range; end

  # source://psych//lib/psych/class_loader.rb#39
  def rational; end

  # source://psych//lib/psych/class_loader.rb#39
  def regexp; end

  # source://psych//lib/psych/class_loader.rb#39
  def struct; end

  # source://psych//lib/psych/class_loader.rb#39
  def symbol; end

  # source://psych//lib/psych/class_loader.rb#32
  def symbolize(sym); end

  private

  # source://psych//lib/psych/class_loader.rb#48
  def find(klassname); end

  # source://psych//lib/psych.rb#15
  def path2class(_arg0); end

  # source://psych//lib/psych/class_loader.rb#52
  def resolve(klassname); end
end

# source://psych//lib/psych/class_loader.rb#9
Psych::ClassLoader::DATA = T.let(T.unsafe(nil), String)

# source://psych//lib/psych/class_loader.rb#77
class Psych::ClassLoader::Restricted < ::Psych::ClassLoader
  # source://psych//lib/psych/class_loader.rb#78
  def initialize(classes, symbols); end

  # source://psych//lib/psych/class_loader.rb#84
  def symbolize(sym); end

  private

  # source://psych//lib/psych/class_loader.rb#96
  def find(klassname); end
end

# source://psych//lib/psych/coder.rb#9
class Psych::Coder
  # source://psych//lib/psych/coder.rb#13
  def initialize(tag); end

  # source://psych//lib/psych/coder.rb#84
  def [](k); end

  # source://psych//lib/psych/coder.rb#78
  def []=(k, v); end

  # source://psych//lib/psych/coder.rb#82
  def add(k, v); end

  # source://psych//lib/psych/coder.rb#10
  def implicit; end

  # source://psych//lib/psych/coder.rb#10
  def implicit=(_arg0); end

  # source://psych//lib/psych/coder.rb#34
  def map(tag = T.unsafe(nil), style = T.unsafe(nil)); end

  # source://psych//lib/psych/coder.rb#73
  def map=(map); end

  # source://psych//lib/psych/coder.rb#10
  def object; end

  # source://psych//lib/psych/coder.rb#10
  def object=(_arg0); end

  # source://psych//lib/psych/coder.rb#54
  def represent_map(tag, map); end

  # source://psych//lib/psych/coder.rb#60
  def represent_object(tag, obj); end

  # source://psych//lib/psych/coder.rb#42
  def represent_scalar(tag, value); end

  # source://psych//lib/psych/coder.rb#48
  def represent_seq(tag, list); end

  # source://psych//lib/psych/coder.rb#24
  def scalar(*args); end

  # source://psych//lib/psych/coder.rb#67
  def scalar=(value); end

  # source://psych//lib/psych/coder.rb#11
  def seq; end

  # source://psych//lib/psych/coder.rb#90
  def seq=(list); end

  # source://psych//lib/psych/coder.rb#10
  def style; end

  # source://psych//lib/psych/coder.rb#10
  def style=(_arg0); end

  # source://psych//lib/psych/coder.rb#10
  def tag; end

  # source://psych//lib/psych/coder.rb#10
  def tag=(_arg0); end

  # source://psych//lib/psych/coder.rb#11
  def type; end
end

# source://psych//lib/psych/exception.rb#23
class Psych::DisallowedClass < ::Psych::Exception
  # source://psych//lib/psych/exception.rb#24
  def initialize(action, klass_name); end
end

class Psych::Emitter < ::Psych::Handler
  # source://psych//lib/psych.rb#15
  def initialize(*_arg0); end

  # source://psych//lib/psych.rb#15
  def alias(_arg0); end

  # source://psych//lib/psych.rb#15
  def canonical; end

  # source://psych//lib/psych.rb#15
  def canonical=(_arg0); end

  # source://psych//lib/psych.rb#15
  def end_document(_arg0); end

  # source://psych//lib/psych.rb#15
  def end_mapping; end

  # source://psych//lib/psych.rb#15
  def end_sequence; end

  # source://psych//lib/psych.rb#15
  def end_stream; end

  # source://psych//lib/psych.rb#15
  def indentation; end

  # source://psych//lib/psych.rb#15
  def indentation=(_arg0); end

  # source://psych//lib/psych.rb#15
  def line_width; end

  # source://psych//lib/psych.rb#15
  def line_width=(_arg0); end

  # source://psych//lib/psych.rb#15
  def scalar(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5); end

  # source://psych//lib/psych.rb#15
  def start_document(_arg0, _arg1, _arg2); end

  # source://psych//lib/psych.rb#15
  def start_mapping(_arg0, _arg1, _arg2, _arg3); end

  # source://psych//lib/psych.rb#15
  def start_sequence(_arg0, _arg1, _arg2, _arg3); end

  # source://psych//lib/psych.rb#15
  def start_stream(_arg0); end
end

# source://psych//lib/psych/handler.rb#13
class Psych::Handler
  # source://psych//lib/psych/handler.rb#110
  def alias(anchor); end

  # source://psych//lib/psych/handler.rb#236
  def empty; end

  # source://psych//lib/psych/handler.rb#93
  def end_document(implicit); end

  # source://psych//lib/psych/handler.rb#230
  def end_mapping; end

  # source://psych//lib/psych/handler.rb#191
  def end_sequence; end

  # source://psych//lib/psych/handler.rb#241
  def end_stream; end

  # source://psych//lib/psych/handler.rb#246
  def event_location(start_line, start_column, end_line, end_column); end

  # source://psych//lib/psych/handler.rb#150
  def scalar(value, anchor, tag, plain, quoted, style); end

  # source://psych//lib/psych/handler.rb#72
  def start_document(version, tag_directives, implicit); end

  # source://psych//lib/psych/handler.rb#225
  def start_mapping(anchor, tag, implicit, style); end

  # source://psych//lib/psych/handler.rb#186
  def start_sequence(anchor, tag, implicit, style); end

  # source://psych//lib/psych/handler.rb#47
  def start_stream(encoding); end

  # source://psych//lib/psych/handler.rb#251
  def streaming?; end
end

# source://psych//lib/psych/handler.rb#16
class Psych::Handler::DumperOptions
  # source://psych//lib/psych/handler.rb#19
  def initialize; end

  # source://psych//lib/psych/handler.rb#17
  def canonical; end

  # source://psych//lib/psych/handler.rb#17
  def canonical=(_arg0); end

  # source://psych//lib/psych/handler.rb#17
  def indentation; end

  # source://psych//lib/psych/handler.rb#17
  def indentation=(_arg0); end

  # source://psych//lib/psych/handler.rb#17
  def line_width; end

  # source://psych//lib/psych/handler.rb#17
  def line_width=(_arg0); end
end

# source://psych//lib/psych/handlers/document_stream.rb#6
class Psych::Handlers::DocumentStream < ::Psych::TreeBuilder
  # source://psych//lib/psych/handlers/document_stream.rb#7
  def initialize(&block); end

  # source://psych//lib/psych/handlers/document_stream.rb#17
  def end_document(implicit_end = T.unsafe(nil)); end

  # source://psych//lib/psych/handlers/document_stream.rb#12
  def start_document(version, tag_directives, implicit); end
end

# source://psych//lib/psych/json/ruby_events.rb#4
module Psych::JSON::RubyEvents
  # source://psych//lib/psych/json/ruby_events.rb#10
  def visit_DateTime(o); end

  # source://psych//lib/psych/json/ruby_events.rb#14
  def visit_String(o); end

  # source://psych//lib/psych/json/ruby_events.rb#17
  def visit_Symbol(o); end

  # source://psych//lib/psych/json/ruby_events.rb#5
  def visit_Time(o); end
end

# source://psych//lib/psych/json/stream.rb#7
class Psych::JSON::Stream < ::Psych::Visitors::JSONTree
  include ::Psych::Streaming
  extend ::Psych::Streaming::ClassMethods
end

# source://psych//lib/psych/json/stream.rb#12
class Psych::JSON::Stream::Emitter < ::Psych::Stream::Emitter
  include ::Psych::JSON::YAMLEvents
end

# source://psych//lib/psych/json/tree_builder.rb#9
class Psych::JSON::TreeBuilder < ::Psych::TreeBuilder
  include ::Psych::JSON::YAMLEvents
end

# source://psych//lib/psych/json/yaml_events.rb#4
module Psych::JSON::YAMLEvents
  # source://psych//lib/psych/json/yaml_events.rb#9
  def end_document(implicit_end = T.unsafe(nil)); end

  # source://psych//lib/psych/json/yaml_events.rb#21
  def scalar(value, anchor, tag, plain, quoted, style); end

  # source://psych//lib/psych/json/yaml_events.rb#5
  def start_document(version, tag_directives, implicit); end

  # source://psych//lib/psych/json/yaml_events.rb#13
  def start_mapping(anchor, tag, implicit, style); end

  # source://psych//lib/psych/json/yaml_events.rb#17
  def start_sequence(anchor, tag, implicit, style); end
end

# source://psych//lib/psych/nodes/alias.rb#9
class Psych::Nodes::Alias < ::Psych::Nodes::Node
  # source://psych//lib/psych/nodes/alias.rb#14
  def initialize(anchor); end

  # source://psych//lib/psych/nodes/alias.rb#18
  def alias?; end

  # source://psych//lib/psych/nodes/alias.rb#11
  def anchor; end

  # source://psych//lib/psych/nodes/alias.rb#11
  def anchor=(_arg0); end
end

# source://psych//lib/psych/nodes/document.rb#12
class Psych::Nodes::Document < ::Psych::Nodes::Node
  # source://psych//lib/psych/nodes/document.rb#45
  def initialize(version = T.unsafe(nil), tag_directives = T.unsafe(nil), implicit = T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/document.rb#60
  def document?; end

  # source://psych//lib/psych/nodes/document.rb#20
  def implicit; end

  # source://psych//lib/psych/nodes/document.rb#20
  def implicit=(_arg0); end

  # source://psych//lib/psych/nodes/document.rb#23
  def implicit_end; end

  # source://psych//lib/psych/nodes/document.rb#23
  def implicit_end=(_arg0); end

  # source://psych//lib/psych/nodes/document.rb#56
  def root; end

  # source://psych//lib/psych/nodes/document.rb#17
  def tag_directives; end

  # source://psych//lib/psych/nodes/document.rb#17
  def tag_directives=(_arg0); end

  # source://psych//lib/psych/nodes/document.rb#14
  def version; end

  # source://psych//lib/psych/nodes/document.rb#14
  def version=(_arg0); end
end

# source://psych//lib/psych/nodes/mapping.rb#15
class Psych::Nodes::Mapping < ::Psych::Nodes::Node
  # source://psych//lib/psych/nodes/mapping.rb#48
  def initialize(anchor = T.unsafe(nil), tag = T.unsafe(nil), implicit = T.unsafe(nil), style = T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/mapping.rb#26
  def anchor; end

  # source://psych//lib/psych/nodes/mapping.rb#26
  def anchor=(_arg0); end

  # source://psych//lib/psych/nodes/mapping.rb#32
  def implicit; end

  # source://psych//lib/psych/nodes/mapping.rb#32
  def implicit=(_arg0); end

  # source://psych//lib/psych/nodes/mapping.rb#56
  def mapping?; end

  # source://psych//lib/psych/nodes/mapping.rb#35
  def style; end

  # source://psych//lib/psych/nodes/mapping.rb#35
  def style=(_arg0); end

  # source://psych//lib/psych/nodes/mapping.rb#29
  def tag; end

  # source://psych//lib/psych/nodes/mapping.rb#29
  def tag=(_arg0); end
end

# source://psych//lib/psych/nodes/node.rb#10
class Psych::Nodes::Node
  include ::Enumerable

  # source://psych//lib/psych/nodes/node.rb#32
  def initialize; end

  # source://psych//lib/psych/nodes/node.rb#68
  def alias?; end

  # source://psych//lib/psych/nodes/node.rb#14
  def children; end

  # source://psych//lib/psych/nodes/node.rb#69
  def document?; end

  # source://psych//lib/psych/nodes/node.rb#39
  def each(&block); end

  # source://psych//lib/psych/nodes/node.rb#29
  def end_column; end

  # source://psych//lib/psych/nodes/node.rb#29
  def end_column=(_arg0); end

  # source://psych//lib/psych/nodes/node.rb#26
  def end_line; end

  # source://psych//lib/psych/nodes/node.rb#26
  def end_line=(_arg0); end

  # source://psych//lib/psych/nodes/node.rb#70
  def mapping?; end

  # source://psych//lib/psych/nodes/node.rb#71
  def scalar?; end

  # source://psych//lib/psych/nodes/node.rb#72
  def sequence?; end

  # source://psych//lib/psych/nodes/node.rb#23
  def start_column; end

  # source://psych//lib/psych/nodes/node.rb#23
  def start_column=(_arg0); end

  # source://psych//lib/psych/nodes/node.rb#20
  def start_line; end

  # source://psych//lib/psych/nodes/node.rb#20
  def start_line=(_arg0); end

  # source://psych//lib/psych/nodes/node.rb#73
  def stream?; end

  # source://psych//lib/psych/nodes/node.rb#17
  def tag; end

  # source://psych//lib/psych/nodes/node.rb#48
  def to_ruby(symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil), parse_symbols: T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/node.rb#66
  def to_yaml(io = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/node.rb#51
  def transform(symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil), parse_symbols: T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/node.rb#57
  def yaml(io = T.unsafe(nil), options = T.unsafe(nil)); end
end

# source://psych//lib/psych/nodes/scalar.rb#8
class Psych::Nodes::Scalar < ::Psych::Nodes::Node
  # source://psych//lib/psych/nodes/scalar.rb#58
  def initialize(value, anchor = T.unsafe(nil), tag = T.unsafe(nil), plain = T.unsafe(nil), quoted = T.unsafe(nil), style = T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/scalar.rb#31
  def anchor; end

  # source://psych//lib/psych/nodes/scalar.rb#31
  def anchor=(_arg0); end

  # source://psych//lib/psych/nodes/scalar.rb#37
  def plain; end

  # source://psych//lib/psych/nodes/scalar.rb#37
  def plain=(_arg0); end

  # source://psych//lib/psych/nodes/scalar.rb#40
  def quoted; end

  # source://psych//lib/psych/nodes/scalar.rb#40
  def quoted=(_arg0); end

  # source://psych//lib/psych/nodes/scalar.rb#67
  def scalar?; end

  # source://psych//lib/psych/nodes/scalar.rb#43
  def style; end

  # source://psych//lib/psych/nodes/scalar.rb#43
  def style=(_arg0); end

  # source://psych//lib/psych/nodes/scalar.rb#34
  def tag; end

  # source://psych//lib/psych/nodes/scalar.rb#34
  def tag=(_arg0); end

  # source://psych//lib/psych/nodes/scalar.rb#28
  def value; end

  # source://psych//lib/psych/nodes/scalar.rb#28
  def value=(_arg0); end
end

# source://psych//lib/psych/nodes/sequence.rb#41
class Psych::Nodes::Sequence < ::Psych::Nodes::Node
  # source://psych//lib/psych/nodes/sequence.rb#73
  def initialize(anchor = T.unsafe(nil), tag = T.unsafe(nil), implicit = T.unsafe(nil), style = T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/sequence.rb#52
  def anchor; end

  # source://psych//lib/psych/nodes/sequence.rb#52
  def anchor=(_arg0); end

  # source://psych//lib/psych/nodes/sequence.rb#58
  def implicit; end

  # source://psych//lib/psych/nodes/sequence.rb#58
  def implicit=(_arg0); end

  # source://psych//lib/psych/nodes/sequence.rb#81
  def sequence?; end

  # source://psych//lib/psych/nodes/sequence.rb#61
  def style; end

  # source://psych//lib/psych/nodes/sequence.rb#61
  def style=(_arg0); end

  # source://psych//lib/psych/nodes/sequence.rb#55
  def tag; end

  # source://psych//lib/psych/nodes/sequence.rb#55
  def tag=(_arg0); end
end

# source://psych//lib/psych/nodes/stream.rb#8
class Psych::Nodes::Stream < ::Psych::Nodes::Node
  # source://psych//lib/psych/nodes/stream.rb#32
  def initialize(encoding = T.unsafe(nil)); end

  # source://psych//lib/psych/nodes/stream.rb#25
  def encoding; end

  # source://psych//lib/psych/nodes/stream.rb#25
  def encoding=(_arg0); end

  # source://psych//lib/psych/nodes/stream.rb#37
  def stream?; end
end

# source://psych//lib/psych/parser.rb#33
class Psych::Parser
  # source://psych//lib/psych/parser.rb#47
  def initialize(handler = T.unsafe(nil)); end

  # source://psych//lib/psych/parser.rb#41
  def external_encoding=(_arg0); end

  # source://psych//lib/psych/parser.rb#38
  def handler; end

  # source://psych//lib/psych/parser.rb#38
  def handler=(_arg0); end

  # source://psych//lib/psych.rb#15
  def mark; end

  # source://psych//lib/psych/parser.rb#61
  def parse(yaml, path = T.unsafe(nil)); end

  private

  # source://psych//lib/psych.rb#15
  def _native_parse(_arg0, _arg1, _arg2); end
end

# source://psych//lib/psych/scalar_scanner.rb#6
class Psych::ScalarScanner
  # source://psych//lib/psych/scalar_scanner.rb#30
  def initialize(class_loader, strict_integer: T.unsafe(nil), parse_symbols: T.unsafe(nil)); end

  # source://psych//lib/psych/scalar_scanner.rb#27
  def class_loader; end

  # source://psych//lib/psych/scalar_scanner.rb#109
  def parse_int(string); end

  # source://psych//lib/psych/scalar_scanner.rb#115
  def parse_time(string); end

  # source://psych//lib/psych/scalar_scanner.rb#38
  def tokenize(string); end
end

# source://psych//lib/psych/scalar_scanner.rb#22
Psych::ScalarScanner::INTEGER_LEGACY = T.let(T.unsafe(nil), Regexp)

# source://psych//lib/psych/scalar_scanner.rb#15
Psych::ScalarScanner::INTEGER_STRICT = T.let(T.unsafe(nil), Regexp)

# source://psych//lib/psych/stream.rb#24
class Psych::Stream < ::Psych::Visitors::YAMLTree
  include ::Psych::Streaming
  extend ::Psych::Streaming::ClassMethods
end

# source://psych//lib/psych/stream.rb#25
class Psych::Stream::Emitter < ::Psych::Emitter
  # source://psych//lib/psych/stream.rb#26
  def end_document(implicit_end = T.unsafe(nil)); end

  # source://psych//lib/psych/stream.rb#30
  def streaming?; end
end

# source://psych//lib/psych/streaming.rb#3
module Psych::Streaming
  # source://psych//lib/psych/streaming.rb#18
  def start(encoding = T.unsafe(nil)); end

  private

  # source://psych//lib/psych/streaming.rb#25
  def register(target, obj); end
end

# source://psych//lib/psych/streaming.rb#4
module Psych::Streaming::ClassMethods
  # source://psych//lib/psych/streaming.rb#8
  def new(io); end
end

# source://psych//lib/psych/syntax_error.rb#5
class Psych::SyntaxError < ::Psych::Exception
  # source://psych//lib/psych/syntax_error.rb#8
  def initialize(file, line, col, offset, problem, context); end

  # source://psych//lib/psych/syntax_error.rb#6
  def column; end

  # source://psych//lib/psych/syntax_error.rb#6
  def context; end

  # source://psych//lib/psych/syntax_error.rb#6
  def file; end

  # source://psych//lib/psych/syntax_error.rb#6
  def line; end

  # source://psych//lib/psych/syntax_error.rb#6
  def offset; end

  # source://psych//lib/psych/syntax_error.rb#6
  def problem; end
end

# source://psych//lib/psych/tree_builder.rb#17
class Psych::TreeBuilder < ::Psych::Handler
  # source://psych//lib/psych/tree_builder.rb#22
  def initialize; end

  # source://psych//lib/psych/tree_builder.rb#103
  def alias(anchor); end

  # source://psych//lib/psych/tree_builder.rb#77
  def end_document(implicit_end = T.unsafe(nil)); end

  # source://psych//lib/psych/tree_builder.rb#44
  def end_mapping; end

  # source://psych//lib/psych/tree_builder.rb#44
  def end_sequence; end

  # source://psych//lib/psych/tree_builder.rb#90
  def end_stream; end

  # source://psych//lib/psych/tree_builder.rb#33
  def event_location(start_line, start_column, end_line, end_column); end

  # source://psych//lib/psych/tree_builder.rb#19
  def root; end

  # source://psych//lib/psych/tree_builder.rb#96
  def scalar(value, anchor, tag, plain, quoted, style); end

  # source://psych//lib/psych/tree_builder.rb#65
  def start_document(version, tag_directives, implicit); end

  # source://psych//lib/psych/tree_builder.rb#44
  def start_mapping(anchor, tag, implicit, style); end

  # source://psych//lib/psych/tree_builder.rb#44
  def start_sequence(anchor, tag, implicit, style); end

  # source://psych//lib/psych/tree_builder.rb#84
  def start_stream(encoding); end

  private

  # source://psych//lib/psych/tree_builder.rb#116
  def pop; end

  # source://psych//lib/psych/tree_builder.rb#111
  def push(value); end

  # source://psych//lib/psych/tree_builder.rb#132
  def set_end_location(node); end

  # source://psych//lib/psych/tree_builder.rb#122
  def set_location(node); end

  # source://psych//lib/psych/tree_builder.rb#127
  def set_start_location(node); end
end

# source://psych//lib/psych/versions.rb#5
Psych::VERSION = T.let(T.unsafe(nil), String)

# source://psych//lib/psych/visitors/depth_first.rb#4
class Psych::Visitors::DepthFirst < ::Psych::Visitors::Visitor
  # source://psych//lib/psych/visitors/depth_first.rb#5
  def initialize(block); end

  private

  # source://psych//lib/psych/visitors/depth_first.rb#11
  def nary(o); end

  # source://psych//lib/psych/visitors/depth_first.rb#20
  def terminal(o); end

  # source://psych//lib/psych/visitors/depth_first.rb#24
  def visit_Psych_Nodes_Alias(o); end

  # source://psych//lib/psych/visitors/depth_first.rb#16
  def visit_Psych_Nodes_Document(o); end

  # source://psych//lib/psych/visitors/depth_first.rb#18
  def visit_Psych_Nodes_Mapping(o); end

  # source://psych//lib/psych/visitors/depth_first.rb#23
  def visit_Psych_Nodes_Scalar(o); end

  # source://psych//lib/psych/visitors/depth_first.rb#17
  def visit_Psych_Nodes_Sequence(o); end

  # source://psych//lib/psych/visitors/depth_first.rb#15
  def visit_Psych_Nodes_Stream(o); end
end

# source://psych//lib/psych/visitors/emitter.rb#4
class Psych::Visitors::Emitter < ::Psych::Visitors::Visitor
  # source://psych//lib/psych/visitors/emitter.rb#5
  def initialize(io, options = T.unsafe(nil)); end

  # source://psych//lib/psych/visitors/emitter.rb#47
  def visit_Psych_Nodes_Alias(o); end

  # source://psych//lib/psych/visitors/emitter.rb#25
  def visit_Psych_Nodes_Document(o); end

  # source://psych//lib/psych/visitors/emitter.rb#41
  def visit_Psych_Nodes_Mapping(o); end

  # source://psych//lib/psych/visitors/emitter.rb#31
  def visit_Psych_Nodes_Scalar(o); end

  # source://psych//lib/psych/visitors/emitter.rb#35
  def visit_Psych_Nodes_Sequence(o); end

  # source://psych//lib/psych/visitors/emitter.rb#19
  def visit_Psych_Nodes_Stream(o); end
end

# source://psych//lib/psych/visitors/json_tree.rb#6
class Psych::Visitors::JSONTree < ::Psych::Visitors::YAMLTree
  include ::Psych::JSON::RubyEvents

  # source://psych//lib/psych/visitors/json_tree.rb#16
  def accept(target); end

  class << self
    # source://psych//lib/psych/visitors/json_tree.rb#9
    def create(options = T.unsafe(nil)); end
  end
end

# source://psych//lib/psych/visitors/to_ruby.rb#473
class Psych::Visitors::NoAliasRuby < ::Psych::Visitors::ToRuby
  # source://psych//lib/psych/visitors/to_ruby.rb#474
  def visit_Psych_Nodes_Alias(o); end
end

# source://psych//lib/psych/visitors/yaml_tree.rb#580
class Psych::Visitors::RestrictedYAMLTree < ::Psych::Visitors::YAMLTree
  # source://psych//lib/psych/visitors/yaml_tree.rb#592
  def initialize(emitter, ss, options); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#605
  def accept(target); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#617
  def visit_Symbol(sym); end
end

# source://psych//lib/psych/visitors/yaml_tree.rb#581
Psych::Visitors::RestrictedYAMLTree::DEFAULT_PERMITTED_CLASSES = T.let(T.unsafe(nil), Hash)

# source://psych//lib/psych/visitors/to_ruby.rb#14
class Psych::Visitors::ToRuby < ::Psych::Visitors::Visitor
  # source://psych//lib/psych/visitors/to_ruby.rb#27
  def initialize(ss, class_loader, symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil)); end

  # source://psych//lib/psych/visitors/to_ruby.rb#38
  def accept(target); end

  # source://psych//lib/psych/visitors/to_ruby.rb#25
  def class_loader; end

  # source://psych//lib/psych/visitors/to_ruby.rb#356
  def visit_Psych_Nodes_Alias(o); end

  # source://psych//lib/psych/visitors/to_ruby.rb#348
  def visit_Psych_Nodes_Document(o); end

  # source://psych//lib/psych/visitors/to_ruby.rb#168
  def visit_Psych_Nodes_Mapping(o); end

  # source://psych//lib/psych/visitors/to_ruby.rb#132
  def visit_Psych_Nodes_Scalar(o); end

  # source://psych//lib/psych/visitors/to_ruby.rb#136
  def visit_Psych_Nodes_Sequence(o); end

  # source://psych//lib/psych/visitors/to_ruby.rb#352
  def visit_Psych_Nodes_Stream(o); end

  private

  # source://psych//lib/psych/visitors/to_ruby.rb#373
  def allocate_anon_data(node, members); end

  # source://psych//lib/psych.rb#15
  def build_exception(_arg0, _arg1); end

  # source://psych//lib/psych/visitors/to_ruby.rb#438
  def deduplicate(key); end

  # source://psych//lib/psych/visitors/to_ruby.rb#55
  def deserialize(o); end

  # source://psych//lib/psych/visitors/to_ruby.rb#455
  def init_with(o, h, node); end

  # source://psych//lib/psych/visitors/to_ruby.rb#447
  def merge_key(hash, key, val); end

  # source://psych//lib/psych/visitors/to_ruby.rb#362
  def register(node, object); end

  # source://psych//lib/psych/visitors/to_ruby.rb#367
  def register_empty(object); end

  # source://psych//lib/psych/visitors/to_ruby.rb#468
  def resolve_class(klassname); end

  # source://psych//lib/psych/visitors/to_ruby.rb#450
  def revive(klass, node); end

  # source://psych//lib/psych/visitors/to_ruby.rb#378
  def revive_data_members(hash, o); end

  # source://psych//lib/psych/visitors/to_ruby.rb#387
  def revive_hash(hash, o, tagged = T.unsafe(nil)); end

  class << self
    # source://psych//lib/psych/visitors/to_ruby.rb#19
    def create(symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil), parse_symbols: T.unsafe(nil)); end
  end
end

# source://psych//lib/psych/visitors/to_ruby.rb#16
Psych::Visitors::ToRuby::DATA_INITIALIZE = T.let(T.unsafe(nil), UnboundMethod)

# source://psych//lib/psych/visitors/visitor.rb#4
class Psych::Visitors::Visitor
  # source://psych//lib/psych/visitors/visitor.rb#5
  def accept(target); end

  private

  # source://psych//lib/psych/visitors/visitor.rb#19
  def dispatch; end

  # source://psych//lib/psych/visitors/visitor.rb#29
  def visit(target); end

  class << self
    # source://psych//lib/psych/visitors/visitor.rb#12
    def dispatch_cache; end
  end
end

# source://psych//lib/psych/visitors/yaml_tree.rb#15
class Psych::Visitors::YAMLTree < ::Psych::Visitors::Visitor
  # source://psych//lib/psych/visitors/yaml_tree.rb#51
  def initialize(emitter, ss, options); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#117
  def <<(object); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#119
  def accept(target); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#88
  def finish; end

  # source://psych//lib/psych/visitors/yaml_tree.rb#40
  def finished; end

  # source://psych//lib/psych/visitors/yaml_tree.rb#41
  def finished?; end

  # source://psych//lib/psych/visitors/yaml_tree.rb#99
  def push(object); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#82
  def start(encoding = T.unsafe(nil)); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#40
  def started; end

  # source://psych//lib/psych/visitors/yaml_tree.rb#42
  def started?; end

  # source://psych//lib/psych/visitors/yaml_tree.rb#94
  def tree; end

  # source://psych//lib/psych/visitors/yaml_tree.rb#386
  def visit_Array(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#412
  def visit_BasicObject(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#286
  def visit_BigDecimal(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#349
  def visit_Class(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#259
  def visit_Complex(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#165
  def visit_Data(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#229
  def visit_Date(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#234
  def visit_DateTime(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#163
  def visit_Delegator(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#144
  def visit_Encoding(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#394
  def visit_Enumerator(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#217
  def visit_Exception(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#273
  def visit_FalseClass(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#275
  def visit_Float(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#362
  def visit_Hash(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#269
  def visit_Integer(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#344
  def visit_Module(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#221
  def visit_NameError(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#400
  def visit_NilClass(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#149
  def visit_Object(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#136
  def visit_Psych_Omap(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#375
  def visit_Psych_Set(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#354
  def visit_Range(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#246
  def visit_Rational(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#225
  def visit_Regexp(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#290
  def visit_String(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#203
  def visit_Struct(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#404
  def visit_Symbol(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#241
  def visit_Time(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#272
  def visit_TrueClass(o); end

  private

  # source://psych//lib/psych/visitors/yaml_tree.rb#426
  def binary?(string); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#537
  def dump_coder(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#502
  def dump_exception(o, msg); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#572
  def dump_ivars(target); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#499
  def dump_list(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#550
  def emit_coder(c, o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#528
  def format_date(date); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#520
  def format_time(time, utc = T.unsafe(nil)); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#532
  def register(target, yaml_obj); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#430
  def visit_array_subclass(o); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#461
  def visit_hash_subclass(o); end

  class << self
    # source://psych//lib/psych/visitors/yaml_tree.rb#44
    def create(options = T.unsafe(nil), emitter = T.unsafe(nil)); end
  end
end

# source://psych//lib/psych/visitors/yaml_tree.rb#16
class Psych::Visitors::YAMLTree::Registrar
  # source://psych//lib/psych/visitors/yaml_tree.rb#17
  def initialize; end

  # source://psych//lib/psych/visitors/yaml_tree.rb#31
  def id_for(target); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#27
  def key?(target); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#35
  def node_for(target); end

  # source://psych//lib/psych/visitors/yaml_tree.rb#23
  def register(target, node); end
end
