#!/bin/bash -e

if [ "$#" != 1 ]; then
    echo "Usage: ./run <mode>"
    echo "0 - User Mode, 1 - Supervisor Mode, 3 - Machine Mode"
    echo "e.g. ./run 0"
    exit 0
fi

kernel=$1

if [ "$1" == "0" ]; then
    echo "Booting into User Mode"
    upper="UMODE"
elif [ "$1" == "1" ]; then
    echo "Booting into Supervisor Mode"
    upper="SMODE"
elif [ "$1" == "3" ]; then
    echo "Booting into Machine Mode"
    upper="MMODE"
fi

echo "Running QEMU from `whereis qemu-system-riscv64`"

make clean
make all MODE=$upper

echo ""
echo "Executing..."
make qemu-gdb 